CREATE TABLE PROVEEDOR
(

IDPROVEEDOR INT PRIMARY KEY AUTO_INCREMENT,
NOMBRE VARCHAR(50),
RUC VARCHAR(20)
);

CREATE TABLE CLIENTE

(
IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
NOMBRES VARCHAR(30),
APELLIDOS VARCHAR(30),
DNI VARCHAR(11),
CELULAR VARCHAR(15),
DIRECCION VARCHAR(50),
IDPROVEEDOR INT
);

INSERT INTO PROVEEDOR (NOMBRE,RUC) VALUES ('YHONAM S.A.C','2087654321');
INSERT INTO CLIENTE (NOMBRES, APELLIDOS, DNI, CELULAR, DIRECCION,IDPROVEEDOR)VALUES('blanca','monrroy','87654321','987654321','plaza bolognesi',1);